[package]
name = "personal_search"
version = "0.1.0"
authors = ["becker <github@deathbyescalator.com>"]
edition = "2018"

[features]
sync = [ "rusqlite" ]
server = ["tokio", "actix-web","actix-cors", "actix-files", "actix-service", "futures", "env_logger", "json"]

[dependencies]
tantivy = "0.13.2"
ureq = "*"
tempfile = "*"
lopdf= "*"
select = "*"
chrono = "*"
lazy_static = "*"
toml = "*"
structopt = "*"
brotli = "*"
serde = { version = "1", features = ["derive"]}
serde_json =  { version = "1" }
glob = "*"
url = "*"
dirs = "*"

probabilistic-collections = { version = "*", features = ["serde"] }
triple_accel =  { version = "*" }
md5 =  { version = "*"}
rust-bert ={ version = "*" }


rusqlite = { version = "*", optional = true, features= ["bundled","chrono","unlock_notify"] }


tokio = { version="*", optional = true}
actix-web =  { version = "3", optional = true }
actix-files =  { version = "*", optional = true }
actix-cors =  { version = "*", optional = true }
actix-service = { version =  "1", optional = true }
futures =  { version = "0.3.1", optional = true }
env_logger = { version =  "0.7", optional = true }
json =  { version = "0.12", optional = true }

[[bin]]
name = "chrome_sync"
path = "src/bin/chrome_sync/main.rs"
features = ["sync"]

[[bin]]
name = "firefox_sync"
path = "src/bin/firefox_sync/main.rs"
features = ["sync"]

[[bin]]
name = "server"
path = "src/bin/server/main.rs"
features = ["server"]
