[package]
name = "personal_search"
version = "0.1.0"
authors = ["becker <github@deathbyescalator.com>"]
edition = "2018"

[features]
firefox_sync = [ "rusqlite", "glob", "dirs" ]
server = [ "actix-web","actix-cors", "actix-files", "serde", "actix-service", "futures", "env_logger", "serde_json", "json"]

[dependencies]
tantivy = "0.13.2"
reqwest = { version = "*", features = ["blocking"] }
select = "*"
tempfile = "*"
chrono = "*"
lazy_static = "*"
toml = "*"
structopt = "*"

probabilistic-collections = { version = "*", features = ["serde"] }
triple_accel =  { version = "*" }
md5 =  { version = "*"}
rust-bert ={ version = "*" }

dirs = { version = "*", optional = true }
rusqlite = { version = "*", optional = true }
glob = { version = "*", optional = true }


actix-web =  { version = "3", optional = true }
actix-files =  { version = "*", optional = true }
actix-cors =  { version = "*", optional = true }
actix-service = { version =  "1", optional = true }
futures =  { version = "0.3.1", optional = true }
env_logger = { version =  "0.7", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json =  { version = "1", optional = true }
json =  { version = "0.12", optional = true }

[[bin]]
name = "firefox_sync"
path = "src/bin/firefox_sync/main.rs"
features = ["firefox_sync"]

[[bin]]
name = "server"
path = "src/bin/server/main.rs"
features = ["server"]
